### ISSUE TITLE
VulScanEngine没有实现？

### ISSUE THREAD

**Issue by hustwyk** [zsdlove/Hades#2]
Hades-cli.py中通过apkvulcheck的run调用了VulScanEngine方法，但是该方法没有实现，导致运行报错，是个怎么回事。。。是我打开方式不对吗=_=

**Comment by zsdlove** [comment]
VulScanEngine这部分是做apk的漏洞检测的，这部分不开源，所以这部分代码去掉了。

**Comment by ehaoxiongdiycw** [comment]
这么坑嘛，没开源？

**Comment by zsdlove** [comment]
已解答，没什么问题close了
